-----------------------------141924416631065136792297947711
Content-Disposition: form-data; name="file"; filename="Makefile"
Content-Type: application/octet-stream

NAME = webserv

# Dossiers
OBJ_DIR = objs
SRC_DIR = srcs
INC_DIR = includes
DEP_DIR = deps

# Création des dossiers nécessaires
$(shell mkdir -p $(OBJ_DIR) $(DEP_DIR))

CC = c++ 

CFLAGS
